name: Bump Cask Versions

on:
  schedule:
    - cron: "0 3,15 * * *"  # Runs at 3:00 AM and 3:00 PM UTC
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        uses: Homebrew/actions/git-user-config@main

      - name: Bump cask versions
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: brew bump --tap ${{ github.repository }} --open-pr --no-fork
